
SUCCESS_RESPONSE_STATUS_CODE = 200

SUCCESS_KEY_INSERT_RESPONSE_STATUS_CODE = 201
SUCCESS_KEY_INSERT_RESPONSE_MESSAGE = "Key created with ID {}"

BAD_REQUEST_STATUS_CODE = 400
BAD_REQUEST_PARAMS_MISSING_MESSAGE = "Request is missing required params."

SEARCH_INVAILD_REQUEST_STATUS_CODE = 400
SEARCH_INVAILD_REQUEST_MESSAGE = "Search request is missing required queryparams."

SEARCH_KEY_NOT_FOUND_STATUS_CODE = 404
SEARCH_KEY_NOT_FOUND_MESSAGE = "No keys found with the given query"

KEY_NOT_FOUND_STATUS_CODE = 404
KEY_NOT_FOUND_MESSAGE = "Key with ID {} could not be found"
